# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jfox <jfox.42angouleme@gmail.com>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/06/17 14:20:05 by jfox              #+#    #+#              #
#    Updated: 2026/08/29 19:35:32 by jfox             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

OBJECT_DIR ?= ./object_files
SRC_DIR = ./src
INC_DIR = ./include

SRC =	main.c \
		tokenize/tokenizing.c tokenize/token_utils.c \
		tokenize/token_validation.c \
		execution/env_to_array.c \
		execution/exec_utils.c execution/exec_handle_redir.c \
		execution/exec_safety_funct.c \
		execution/execution.c execution/execution_child.c \
		execution/exec_get_path.c execution/exec_check_stat.c \
		execution/init/exec_init_pipefd.c \
		execution/exec_builtin/exec_builtin.c \
		execution/exec_builtin/exec_child_builtin.c \
		execution/exec_heredoc/exec_handle_heredoc.c \
		execution/exec_heredoc/exec_heredoc_expand.c \
		execution/exec_heredoc/exec_heredoc_utils.c \
		environment/environment.c environment/environment_utils.c \
		environment/environment_utils_free.c \
		expansion/process.c expansion/expand_tokens.c \
		expansion/expand_utils.c expansion/expand_utils_set_quotes.c \
		expansion/expand_utils_fieldexpansion.c \
		parsing/parsing.c parsing/parsing_redirects.c \
		parsing/parsing_heredoc.c \
		builtins/builtin_utils.c \
		builtins/cd.c builtins/pwd.c \
		builtins/export.c builtins/export_utils.c \
		builtins/export_utils_append.c \
		builtins/echo.c \
		builtins/exit.c builtins/exit_utils.c \
		signal/signal_child.c signal/signal_parent.c\
		shell/shell.c shell/free_utils.c shell/free_shell.c

NAME = minishell
OBJ = $(SRC:%.c=$(OBJECT_DIR)/%.o)

CC = cc
CFLAGS += -Wall -Wextra -Werror -g -I$(INC_DIR) -MMD -MP

TOOLS = libft.a

USRPATH = $(shell pwd)

# ---------- OS detection ---------- // AI GENERATED BY CLAUDE
UNAME_S := $(shell uname -s)

ifeq ($(UNAME_S),Darwin)
	# Homebrew readline is keg-only on macOS, so it isn't on the default
	# include/lib search path. Detect Apple Silicon vs Intel prefix.
	ifneq ($(wildcard /opt/homebrew/opt/readline),)
		READLINE_PREFIX = /opt/homebrew/opt/readline
	else
		READLINE_PREFIX = /usr/local/opt/readline
	endif
	CFLAGS += -I$(READLINE_PREFIX)/include
	LDFLAGS += -L$(READLINE_PREFIX)/lib -lreadline
else
	LDFLAGS += -lreadline
endif

all: $(NAME) ping_make

# ---------- Build objects ----------
$(OBJECT_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(dir $@)
	@$(CC) -o $@ -c $< $(CFLAGS)

# --------- Build minishell ----------
$(NAME): $(TOOLS) $(OBJ)
	@$(CC) $(CFLAGS) -o $(NAME) $(OBJ) $(TOOLS) $(LDFLAGS)
	@echo "\033[32m--------The minishell executable and object files have been made--------\033[0m"

# -------- Utility libraries --------
$(TOOLS):
	@$(MAKE) -C libft

clean:
	@rm -rf $(OBJECT_DIR)
	@echo "\033[33m-----The minishell and libft Object_Files were removed successfully-----\033[0m"

fclean: clean
	@rm -f $(NAME)
	@echo "\033[33m--------------The executable has been removed successfully--------------\033[0m"
	@$(MAKE) fclean -C libft
	@echo "\033[33m"
	@echo "=============================CLEAN COMPLETE============================="
	@echo "\033[0m"

re: ping_re fclean all

ping_make:
	@echo "\033[32m"
	@echo "=============================MAKE COMPLETE=============================="
	@echo "\033[0m"

ping_re:
	@echo "\033[31m"
	@echo "=======================REBUILDING THE EXECUTABLE========================"
	@echo "\033[0m"

valgrind: $(NAME)
	@echo clear && valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --track-fds=yes --trace-children=yes --suppressions=$(USRPATH)/readline.supp ./minishell

.PHONY: all clean fclean re tools ping_make ping_re valgrind

-include $(OBJ:.o=.d)
