/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   tokenizing_og.c                                    :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: pking <pking@student.42.fr>                +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/06/17 15:44:36 by jfox              #+#    #+#             */
/*   Updated: 2026/07/29 18:21:11 by pking            ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "minishell.h"

// ONLY INCLUDED IN THE BUNDLE FOR HISTORICAL DOCUMENTATION PURPOSES;
// ~~~~~~~~~~~~~~~~~~~~~DEPRECATED~~~~~~~~~~~~~~~~~~~~~//



//goes thru the word until the end to find the last char
static int	find_end_word(char *input, int i, int *word_start)
{
	char	quote_type;

	if ((input[i] == '"' || input[i] == '\''))
	{
		quote_type = input[i];
		i++;
		*word_start = i;
		while (input[i] && input[i] != quote_type)
			i++;
		if (!input[i])
			return (-1);
		if (input[i] == quote_type)
			i++; //fixes the i to be at index outside the quotes
	}
	else
	{
		while (input[i] && input[i] != ' ' && input[i] != '\t'
			&& input[i] != '|' && input[i] != '<' && input[i] != '>')
			i++;
	}
	return (i);
}

// Our Helper for get_type. Returns Enum. Single Char Checker.
static t_token_type	get_type(char *value, int i)
{
	if (value[i] == '|')
		return (PIPE);
	if (value[i] == '<')
	{
		if (value[i + 1] == '<')
			return (HEREDOC);
		else
			return (REDIR_IN);
	}
	if (value[i] == '>')
	{
		if (value[i + 1] == '>')
			return (APPEND);
		else
			return (REDIR_OUT);
	}
	if (value[i] == '"' || value[i] == '\'')
	{
		if (value[i] == '"')
			return (WORD | D_QUOTED);
		else
			return (WORD | S_QUOTED);
	}
	return (WORD);
}

// Helper Function to make a New Token Node
t_token	*make_new_token(t_token_type type, char *value)
{
	t_token	*new_token;

	new_token = ft_calloc(1, sizeof(t_token));
	if (!new_token)
		return (NULL);
	new_token->type = type;
	new_token->value = value;
	new_token->next = NULL;
	return (new_token);
}

// Gonna need some helper functions here, function is too long!
t_token	*tokenize(char *input, t_token *head, t_token *tail, t_token *new)
{
	int		word_start;
	int		i;
	int		token_len;

	word_start = 0;
	i = 0;
	if (!input)
		return (NULL);
	while (input[i])
	{
		while ((input[i] >= 9 && input[i] <= 13) || input [i] == ' ')
			i++;
		if (!input[i])
			break ;
		word_start = i;
		if (input[i] == '|' || input[i] == '<' || input[i] == '>')
		{
			if (input[i] == '<' && input[i + 1] == '<')
				i++;
			if (input[i] == '>' && input[i + 1] == '>')
				i++;
			i++;
			token_len = i - word_start;
		}
		else
		{ // this condition was generated by gemini
			// G: If we parsed a closed quote, 'i' was incremented past closing quote,
			// so the actual inner string length is (i - 1 - word_start)
			i = find_end_word(input, i, &word_start);
			if (input[word_start - 1] == '\'' || input[word_start - 1] == '"')
			{
				if (input[i - 1] == input[word_start - 1]) // if beginning quote type == end quote type
					token_len = i - 1 - word_start; // what happens w diff quote types
				else 
					{
						write (2, "minishell: syntax error: unclosed quote\n", 40);
						free_tokens(&head);
						return (NULL);
					} // Unclosed quote edge case. Normally opens dsquote doc
			}
			else
				token_len = i - word_start;
		}
		new = make_new_token(get_type(input, word_start),
				ft_substr(input, word_start, token_len));
		if (!new)
		{
			free_tokens(&head);
			return (NULL);
		}
		if (!head)
			head = new;
		else
			tail->next = new;
		tail = new;
	}
	return (head);
}
